### ISSUE TITLE
Add an option to ungroup tabs

### ISSUE THREAD

**Issue by Binero** [gnumdk/eolie#275] opened 2017-11-01 19:06 UTC
While grouping the tabs really helps for organisation, when browsing it can be frustrating as we have to click twice to open a tab as opposed to once. 

As such, it would be preferable to have a toggle in the preferences panel that allows the user to not group tabs.

**Comment by gnumdk** [comment] 2017-11-01 23:09
By design, wont fix. There is enough browsers with tabs.

**Closed by gnumdk** 2017-11-01 23:09 UTC

**Comment by gnumdk** [comment] 2017-11-10 10:08
@Binero Good news: https://youtu.be/aRVL_T7i5HQ

Found a way to make switch faster. But not compatible with minimal sidebar ;)
