### ISSUE TITLE
Eolie crashes during download

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnumdk/eolie#2] opened 2017-02-07 01:05 UTC
Eolie crashes when you try to download a file that exists instead of asking the user to replace it or rename it to something else `filename (i)`
```
DownloadManager::__on_failed: WebKitDownloadError: Error opening file '/home/bilal/Downloads/elementaryos-0.4-stable-amd64.20160921.iso': File exists (401)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eolie/toolbar_end.py", line 124, in __on_download_changed
    GLib.source_remove(self.__timeout_id)
TypeError: Argument 0 does not allow None as a value
```
Does using get_destination and see if the destination exists on download manager and settings a new destination would work? 
Edit: i did some digging, it seems that getting the destination just after the download is started will return a None object, you need to wait until `created-destination` signal is emitted

**Comment by gnumdk** [comment] 2017-02-17 13:26
As I rewrite this code since you open the bug. Closing but reopen if you manage to reproduce.

**Closed by gnumdk** 2017-02-17 13:26 UTC
