### ISSUE TITLE
Eolie does not remember previous pages on start up 

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#273] opened 2017-11-01 05:25 UTC
### Environment
- Eolie version: 0.9.9
- GTK+ version: 3.22
- Operating system: Linux christoforos-Lenovo-G50-80 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Hi.
Lets say that I have 3 windows (pages) open.
If I close Eolie and reopen,  it remembers just one and the others are empty and can not be open.
If I close it again, Eolie opens with only one window.
In preference this choice is checked (previous pages on start up).

**Comment by gnumdk** [comment] 2017-11-01 11:37
Fixed in master.

**Comment by cgiannakidis70** [comment] 2017-11-01 13:40
Same thing and another weird thing.After first close  I reopen and with sidebar visible hover mouse over one  of those empty windows make Eolie crash.

**Comment by gnumdk** [comment] 2017-11-01 13:41
I need logs ;)

**Comment by cgiannakidis70** [comment] 2017-11-01 13:43
From terminal:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eolie/sites_manager_child.py", line 277, in __on_query_tooltip
    tooltip += "\n%s" % GLib.markup_escape_text(title)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 490, in markup_escape_text
    return GLib.markup_escape_text(text, length)
TypeError: Argument 0 does not allow None as a value

**Comment by gnumdk** [comment] 2017-11-01 14:21
Crash fixed.

For session, management, how do you close Eolie?

**Comment by cgiannakidis70** [comment] 2017-11-01 14:23
from close button

**Comment by gnumdk** [comment] 2017-11-01 14:42
So it's normal for me, does it work in Firefox?

**Comment by gnumdk** [comment] 2017-11-01 14:44
Oh yes, it works in firefox, looks strange for me to re-open closed windows.

**Comment by gnumdk** [comment] 2017-11-01 14:46
But chromium does like Eolie...

**Comment by cgiannakidis70** [comment] 2017-11-01 14:55
Thank you for fixing crash.But Eolie does not remember previous pages on start up.

**Comment by gnumdk** [comment] 2017-11-01 15:03
It remember if you quit eolie, if you close windows, it will only remember the last one.

**Comment by gnumdk** [comment] 2017-11-01 15:03
Like chromium

**Comment by cgiannakidis70** [comment] 2017-11-01 15:10
So you say that it's not like chrome  where you have the choice "Continue where you left off"?

**Comment by gnumdk** [comment] 2017-11-01 15:14
On chrome, it only works if you quit chromium, if you close windows, it only open up the last one.

**Comment by gnumdk** [comment] 2017-11-01 15:15
But I'm working on a fix ;)

**Comment by cgiannakidis70** [comment] 2017-11-01 15:15
OK.

**Comment by gnumdk** [comment] 2017-11-01 15:18
It now keeps windows in cache for 25 seconds, should be enough.

**Comment by cgiannakidis70** [comment] 2017-11-01 15:20
To clarify it:

1.Eolie is open with 4 pages
![screenshot from 2017-11-01 17-13-07](https://user-images.githubusercontent.com/33185625/32281766-7dcc01fc-bf28-11e7-89f6-bbdfe795d8c8.png)

2.I close from close button (Eolie not a window) and re-open Eolie
![screenshot from 2017-11-01 17-13-42](https://user-images.githubusercontent.com/33185625/32281890-cb65774a-bf28-11e7-9ae8-846f1de9ccab.png)

3.I close Eolie again and re-open
![screenshot from 2017-11-01 17-14-19](https://user-images.githubusercontent.com/33185625/32281933-eb74b0aa-bf28-11e7-8e53-61b0156239dd.png)

**Comment by gnumdk** [comment] 2017-11-01 15:37
Ok, I understand your issue, it's because page are not reloaded on start.

**Comment by cgiannakidis70** [comment] 2017-11-01 18:50
Hi again.
I just built  from git Eolie and it runs smoothly. Thank you a lot and I appreciate your work.

**Comment by gnumdk** [comment] 2017-11-02 10:09
Add some more code to save title, order and restore preview when offloaded. Tell me if you find any regression ;)

**Comment by cgiannakidis70** [comment] 2017-11-02 10:40
Hi.As far as now, it works ok.
But there is an issue with the addresses. In overview with, let's say, 4 windows open, I select a window, the window loads, but in address bar  the address does not refresh.It shows the previous one when the mouse hovers on the address bar.

**Comment by gnumdk** [comment] 2017-11-02 10:45
I guess this one is fixed ;)

**Comment by cgiannakidis70** [comment] 2017-11-02 19:02
Hi.
Both issues are fixed. Eolie is ok.

**Closed** 2017-11-03 10:28 UTC
